# apiVersion: source.toolkit.fluxcd.io/v1
# kind: GitRepository
# metadata:
#   name: oes-gitrepo
#   namespace: oesgitops-config
# spec:
#   interval: 1m0s
#   timeout: 3m0s
#   ref:
#     branch: master
#   secretRef:
#     name: git-fluxconfig-credentials
#   url: ssh://git@github.com/AlexPankratov1992/gitops-flux2-kustomize-helm-mt
