apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: notesapp-repo-policy
  namespace: oesgitops-config
spec:
  imageRepositoryRef:
    name: notesapp-repo
  policy:
    numerical: {}