apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: notesapp-repo-policy
  namespace: oesgitops-config
spec:
  imageRepositoryRef:
    name: notesapp-repo
  policy:
    semver:
      range: ">=1.0.0, <20.0.0"  # Define your Semver range here