apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notesapp-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - notesapp.d9bcc6aece5445d2bb67.eastus.aksapp.io
    secretName: tls-secret
  rules:
  - host: notesapp.d9bcc6aece5445d2bb67.eastus.aksapp.io
    http: 
        paths: 
        - backend:
            service:
              name: notesapp-service
              port: 
                  number: 4000
          path: /
          pathType: Prefix 