apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-config
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 3m0s
  ref:
    branch: master
  secretRef:
    name: git-fluxconfig-credentials
  url: https://github.com/AlexPankratov1992/gitops-flux2-kustomize-helm-mt
